### ISSUE TITLE
Should this crate move to the rust-bitcoin organisation?

### ISSUE THREAD

**Issue by tcharding** [rust-bitcoin/bitcoind#149]
`bitcoind` is depended on by `rust-miniscript`, as such upgrading it requires upgrading `bitcoind`. Would it be better if `bitcoind` lived in the `github.com/rust-bitcoin` org and some of the maintenance burden was shared around?

**Comment by tcharding** [comment]
cc https://github.com/rust-bitcoin/rust-bitcoin/discussions/2199

**Comment by RCasatta** [comment]
Note that this crate other than me already has @apoelstra  and @LeoComandini as mantainers. Also, on crates.io there is me and leo.

I am ok in moving the repo in the rust-bitcoin organization

**Comment by apoelstra** [comment]
I wouldn't mind having it in the org; I think it has just as much right to be in the org as rust-bitcoincore-rpc does. And I would love if the maintainership was "shared around" .... but also like rust-bitcoincore-rpc, I personally usually don't enjoy working on this crate because it involves "ugly" stuff around creating and tracking processes, HTTP, etc., and there's a constant maintenance burden caused by Core's constant updates.

**Comment by RCasatta** [comment]
From what I read I think I need permission to create repository under rust-bitcoin to make the transfer. Or let me know what I have to do

**Comment by apoelstra** [comment]
I sent you a member invite, which should be sufficient.

**Comment by RCasatta** [comment]
Moved
